# .air.toml

# Define o diretório raiz do projeto
root = "."

# Define os arquivos que devem ser monitorados pelo air
[[watcher]]
  paths = ["."]

# Define as configurações do servidor
[server]
  # Define a porta do servidor
  port = 8080

  # Define o host do servidor
  host = "localhost"

  # Define o tempo limite do servidor
  read_timeout = "30s"
  write_timeout = "30s"
