definitions:
  github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  handler.CreateCompanyRequest:
    properties:
      address:
        type: string
      addressCity:
        type: string
      addressComplement:
        type: string
      addressNumber:
        type: string
      addressState:
        type: string
      addressZipCode:
        type: string
      cnpj:
        type: string
      name:
        type: string
    type: object
  handler.CreateCompanyResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.CompanyResponse'
      message:
        type: string
    type: object
  handler.CreateUserRequest:
    properties:
      address:
        type: string
      companyId:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      type:
        type: string
    type: object
  handler.CreateUserResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.UserResponse'
      message:
        type: string
    type: object
  handler.DeleteCompanyResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.CompanyResponse'
      message:
        type: string
    type: object
  handler.DeleteUserResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.UserResponse'
      message:
        type: string
    type: object
  handler.ListCompaniesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.CompanyResponse'
        type: array
      message:
        type: string
    type: object
  handler.ListUsersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.UserResponse'
        type: array
      message:
        type: string
    type: object
  handler.ShowCompanyResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.CompanyResponse'
      message:
        type: string
    type: object
  handler.ShowUserResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.UserResponse'
      message:
        type: string
    type: object
  handler.UpdateCompanyRequest:
    properties:
      address:
        type: string
      addressCity:
        type: string
      addressComplement:
        type: string
      addressNumber:
        type: string
      addressState:
        type: string
      addressZipCode:
        type: string
      cnpj:
        type: string
      name:
        type: string
    type: object
  handler.UpdateCompanyResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.CompanyResponse'
      message:
        type: string
    type: object
  handler.UpdateUserRequest:
    properties:
      address:
        type: string
      companyId:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      type:
        type: string
    type: object
  handler.UpdateUserResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.UserResponse'
      message:
        type: string
    type: object
  schemas.CompanyResponse:
    properties:
      address:
        type: string
      addressCity:
        type: string
      addressComplement:
        type: string
      addressNumber:
        type: string
      addressState:
        type: string
      addressZipCode:
        type: string
      cnpj:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      users:
        items:
          $ref: '#/definitions/schemas.UserResponse'
        type: array
    type: object
  schemas.UserResponse:
    properties:
      address:
        type: string
      companyId:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /companies:
    get:
      consumes:
      - application/json
      description: List all Companies
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListCompaniesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
      summary: List Companies
      tags:
      - Company
  /company:
    delete:
      consumes:
      - application/json
      description: Delete a company
      parameters:
      - description: Company identification
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteCompanyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
      summary: Delete Company
      tags:
      - Company
    get:
      consumes:
      - application/json
      description: Show a company
      parameters:
      - description: Company identification
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowCompanyResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
      summary: Show Company
      tags:
      - Company
    post:
      consumes:
      - application/json
      description: Create a new company
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateCompanyRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateCompanyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
      summary: Create Company
      tags:
      - Company
    put:
      consumes:
      - application/json
      description: Update a new company
      parameters:
      - description: Company identification
        in: query
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateCompanyRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.UpdateCompanyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_company.ErrorResponse'
      summary: Update Company
      tags:
      - Company
  /user:
    delete:
      consumes:
      - application/json
      description: Delete a user
      parameters:
      - description: User identification
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DeleteUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
      summary: Delete User
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Show a user
      parameters:
      - description: User identification
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowUserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
      summary: Show User
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
      summary: Create User
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update a new user
      parameters:
      - description: User identification
        in: query
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
      summary: Update User
      tags:
      - User
  /users:
    get:
      consumes:
      - application/json
      description: List all Users
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListUsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_LuisMarchio03_acim-backend_handler_user.ErrorResponse'
      summary: List Users
      tags:
      - User
swagger: "2.0"
